<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Date And Time_dateAndTimePickerInput</name>
   <tag></tag>
   <elementGuidId>fbdfa968-cebc-44e0-a629-5d34ee793fa1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dateAndTimePickerInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dateAndTimePickerInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#dateAndTimePickerInput</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>28874214-5c92-4d93-867a-6160110ed6aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2f990e4c-d678-4761-bd51-29ce705295d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dateAndTimePickerInput</value>
      <webElementGuid>bf9b8a88-8269-4f2c-b9dc-9ecee30dd609</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>react-datepicker-ignore-onclickoutside</value>
      <webElementGuid>01d82fce-f1eb-40d0-b2ae-adf6c0c37867</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>February 17, 2025 2:54 PM</value>
      <webElementGuid>67f3991e-a162-4fef-abf0-d665de424f57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dateAndTimePickerInput&quot;)</value>
      <webElementGuid>0ebe5b54-cbc3-4d03-92e2-a5d3b191fd2c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dateAndTimePickerInput']</value>
      <webElementGuid>9e2c5df3-3dba-426d-9bac-caee353ea657</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dateAndTimePicker']/div/div/input</value>
      <webElementGuid>16686c20-591e-4ae2-a802-8d31212ab9e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/input</value>
      <webElementGuid>912f0450-30e3-4728-9365-85cb32171d74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'dateAndTimePickerInput']</value>
      <webElementGuid>bcb631d1-89e3-4f85-809f-0b8f18881c7c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
