<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_BseLogin</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>1c25acf7-66f1-4ac8-84dd-812f0a76c4c0</testSuiteGuid>
   <testCaseLink>
      <guid>805b1b2d-755d-4414-8f52-450b1117a3d0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/BSEQA/BSE-LOGIN/TC_BSE-Login</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a709edef-6702-408f-95d0-9e059b16290f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8ddb7bf0-04d1-4e51-bae8-dffb2dd5867c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>018cf57f-d564-40e7-9fe8-1393e1627bd7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6a1e3b53-6899-4f60-9126-e4a23ca47860</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/BSEQA/BSE-LOGOUT/TC_BSE-logout</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>66d12c3f-56f5-435e-bcbb-cca6dce4d542</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>607a9e98-877d-43aa-8515-79f1014268df</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a784616a-2c21-4d7f-8e9b-8fa2bf2bca53</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
