<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Onboarding</name>
   <tag></tag>
   <elementGuidId>f1ac43e1-0f22-4d00-a810-c0785c1a7c25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='flush-collapse130']/div/ul/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#flush-collapse130 > div.accordion-body > ul.list-group.list-group-flush.sidebar-inner-menu > li.list-group-item.border-0.py-1 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Onboarding&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c3f07c69-ea2a-45cb-a1be-da02b450c02d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>routerlinkactive</name>
      <type>Main</type>
      <value>active-link</value>
      <webElementGuid>ea7cee93-e9e2-4629-be81-765c8a065695</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#/member/list</value>
      <webElementGuid>0263b011-53d1-474f-b33c-dc591ec4114b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Onboarding </value>
      <webElementGuid>9e1671c4-7554-4548-9133-b440e1f84087</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;flush-collapse130&quot;)/div[@class=&quot;accordion-body&quot;]/ul[@class=&quot;list-group list-group-flush sidebar-inner-menu&quot;]/li[@class=&quot;list-group-item border-0 py-1&quot;]/a[1]</value>
      <webElementGuid>293e0a8a-c3ea-40f4-ac1f-3971826460ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flush-collapse130']/div/ul/li/a</value>
      <webElementGuid>faa9caf9-2645-465c-be87-8b7292680dc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Onboarding')])[2]</value>
      <webElementGuid>51094556-cfcd-46da-aa56-dff3a4eca15d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Member'])[1]/following::a[1]</value>
      <webElementGuid>e36937d5-4311-4a25-821d-0bf0c64a9c62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order'])[1]/following::a[1]</value>
      <webElementGuid>f90af453-1acb-4df1-921f-db91e1d08fc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Suspension'])[1]/preceding::a[1]</value>
      <webElementGuid>6682d152-44df-49e7-96c4-90345cc366b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Threshold'])[1]/preceding::a[2]</value>
      <webElementGuid>ccf32313-6bea-4bab-9e4e-8146ed31e7e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#/member/list')]</value>
      <webElementGuid>4cdf6c8f-4551-4c45-a5bb-3b6894e32a66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/ul/li/a</value>
      <webElementGuid>2899fb8e-9e26-4da4-885c-542c0fc68483</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#/member/list' and (text() = ' Onboarding ' or . = ' Onboarding ')]</value>
      <webElementGuid>8b804b3c-ea25-4963-a79b-2a5724e2f386</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
