<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add</name>
   <tag></tag>
   <elementGuidId>4cae45b4-3822-4ce8-8aa2-4738861cdfd5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-content']/div/app-member/div/div/section/app-page-title/section/div/div[3]/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-primary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Add&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b289867d-cdef-4028-8b58-3433180b9318</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>f66bb963-b4ad-466a-9075-d8c7d35d5fee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Add </value>
      <webElementGuid>f4413253-b355-4e4c-ba7e-1179ddabec98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;body-content body-bg&quot;]/app-member[1]/div[@class=&quot;member-onboarding-page&quot;]/div[@class=&quot;container-fluid&quot;]/section[@class=&quot;breadcrumbs-wrapper&quot;]/app-page-title[1]/section[@class=&quot;page-heading py-4&quot;]/div[@class=&quot;row justify-content-between align-items-center&quot;]/div[@class=&quot;col-auto&quot;]/div[@class=&quot;outline-button-wrapper&quot;]/button[@class=&quot;btn btn-primary&quot;]</value>
      <webElementGuid>eddbac70-d60a-4fcf-9620-9c5ceb6165d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content']/div/app-member/div/div/section/app-page-title/section/div/div[3]/div/button</value>
      <webElementGuid>3d7dbe4f-9dc9-419f-ba36-369f98ab7ca5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Member Details'])[1]/following::button[1]</value>
      <webElementGuid>88d9a62e-b411-4fd9-ac19-4ee23af1d09e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Onboarding'])[3]/following::button[1]</value>
      <webElementGuid>324af402-f941-4594-839b-23434772fbbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Approved (51538)'])[1]/preceding::button[1]</value>
      <webElementGuid>35869a31-be75-4737-80aa-cee6cbafb93b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pending Approval (13)'])[1]/preceding::button[2]</value>
      <webElementGuid>9ebe813c-4ce3-4622-8ef2-582999e436ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add']/parent::*</value>
      <webElementGuid>6ed19473-73f6-47d7-941c-25a6ad92038b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/button</value>
      <webElementGuid>7ab9f1e9-d449-4e02-92d7-321ca48126e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = ' Add ' or . = ' Add ')]</value>
      <webElementGuid>cdfb772f-b540-4879-a682-1df4765ea051</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
