<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_E_pi pi-bars</name>
   <tag></tag>
   <elementGuidId>2cc19a0b-259e-46a9-8511-f20ae9b87e36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='header']/div/div/div/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.pi.pi-bars</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>i >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>7609c589-aeeb-4044-a140-1dda5fb97689</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pi pi-bars</value>
      <webElementGuid>68c85039-2962-4e1a-81d5-bb4cf59fadea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row align-items-center flex-nowrap&quot;]/div[@class=&quot;col-auto align-items-center d-xl-none mobile-menu&quot;]/i[@class=&quot;pi pi-bars&quot;]</value>
      <webElementGuid>213df4bc-3025-43d6-903b-046de6224f2e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='header']/div/div/div/i</value>
      <webElementGuid>cacf444b-6f35-4afc-b021-f5bf042a1f41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>8d2f73c1-3da0-4aca-8294-a713ec28950e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
