<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_html1body1div4div4iframe1_c-3nqjm2o5ab7o</name>
   <tag></tag>
   <elementGuidId>6c4eca7a-ac30-4a14-a25a-e8348b297a48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='c-3nqjm2o5ab7o']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;c-3nqjm2o5ab7o&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;c-3nqjm2o5ab7o&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>63f0aaba-059f-46c6-b004-01f8df4925a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>recaptcha challenge expires in two minutes</value>
      <webElementGuid>f62c9b59-a608-455d-9091-ebf53d1ff722</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>c-3nqjm2o5ab7o</value>
      <webElementGuid>ebbb2010-bac2-49dd-aed5-518c40c88051</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>809c97fe-d919-4f2c-9462-adf138dbd0b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>fca325f1-4d91-425a-8997-fc5051ac65b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox allow-storage-access-by-user-activation</value>
      <webElementGuid>29a74bf5-6034-42b9-be6d-c325d6941de8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/bframe?hl=en&amp;v=IyZ984yGrXrBd6ihLOYGwy9X&amp;k=6LdsKacZAAAAAIxY1X8GuHZljebmKWs8JGp97UK7</value>
      <webElementGuid>6d6e999f-30fb-401c-8f69-0ad96d6c37d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[4]/div[4]/iframe[1]</value>
      <webElementGuid>d2b25028-ba35-429e-8358-87adab97909b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='c-3nqjm2o5ab7o']</value>
      <webElementGuid>34d0d93d-1893-4a62-9fe7-6d76e3572aee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/iframe</value>
      <webElementGuid>5bb8f144-b482-488e-b499-8e8338d90b1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'recaptcha challenge expires in two minutes' and @name = 'c-3nqjm2o5ab7o' and @src = 'https://www.google.com/recaptcha/api2/bframe?hl=en&amp;v=IyZ984yGrXrBd6ihLOYGwy9X&amp;k=6LdsKacZAAAAAIxY1X8GuHZljebmKWs8JGp97UK7']</value>
      <webElementGuid>2f3221d5-461f-4082-baf0-127b86ecba2e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
