<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_VolvoSaabOpelAudi</name>
   <tag></tag>
   <elementGuidId>c632912b-30b5-42c2-9ecd-1eab21387d77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cars']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cars</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#cars</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>af9c97fa-f7eb-4cf9-9251-54c7cc37a812</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cars</value>
      <webElementGuid>07b029cb-913d-471c-b63a-075d4f524f10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cars</value>
      <webElementGuid>44d3949e-ea43-4ba9-b6f5-2f0e8b0129b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>VolvoSaabOpelAudi</value>
      <webElementGuid>df398871-95ba-4e7c-9dfd-da13e37a232e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cars&quot;)</value>
      <webElementGuid>9b80efbb-2af2-4a5e-a75b-4877b6269db4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cars']</value>
      <webElementGuid>7716c8fb-c392-432b-ab3e-de1dd12be2d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='selectMenuContainer']/div[8]/div/select</value>
      <webElementGuid>ec7ad562-ff44-47df-bc3d-35a5b104ae91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Standard multi select'])[1]/following::select[1]</value>
      <webElementGuid>0f5863ea-5be4-4054-abe0-54eaa4fa1e2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Green'])[2]/following::select[1]</value>
      <webElementGuid>c7197905-0d00-4bfa-875a-42ed34f61ac2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='© 2013-2020 TOOLSQA.COM | ALL RIGHTS RESERVED.'])[1]/preceding::select[1]</value>
      <webElementGuid>79ea3aee-eb3e-431b-b312-a619762fb6f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/select</value>
      <webElementGuid>0a447efb-8ab0-46ab-99a3-759b3fbcc0dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'cars' and @id = 'cars' and (text() = 'VolvoSaabOpelAudi' or . = 'VolvoSaabOpelAudi')]</value>
      <webElementGuid>1ee45a80-e454-4236-bf57-5ecb6d712113</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Red'])[2]/following::select[1]</value>
      <webElementGuid>6dcc4e5b-a369-4f96-8268-42e92f0f819b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
