<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Where does it come from</name>
   <tag></tag>
   <elementGuidId>178ce47d-edea-4ac6-8154-c4bd00485a5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#section2Heading</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='section2Heading']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Where does it come from?&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4762f8ca-2989-4cdb-86e8-e7790608b594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-header</value>
      <webElementGuid>37a9eb6e-027f-4561-9769-9d194689c336</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>section2Heading</value>
      <webElementGuid>aa653cbf-edc3-4a34-a113-0bbadb0f484b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Where does it come from?</value>
      <webElementGuid>1b823701-0f7e-4dbc-a6cd-87a817b32bca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;section2Heading&quot;)</value>
      <webElementGuid>d94255e9-007c-4823-b2b9-53efdafdb0c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='section2Heading']</value>
      <webElementGuid>56b4a832-31bc-4f52-a36f-39831f59452b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordianContainer']/div/div[2]/div</value>
      <webElementGuid>3e6fe395-15eb-42c7-9f6f-470f2b3e0f08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='What is Lorem Ipsum?'])[1]/following::div[4]</value>
      <webElementGuid>f9dfd565-d834-465a-9540-c52bbfe3dc2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accordian'])[2]/following::div[7]</value>
      <webElementGuid>06e0d44f-18af-49a3-9d6b-0d4a9dc89ab8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Why do we use it?'])[1]/preceding::div[3]</value>
      <webElementGuid>38ec8783-e177-4ef7-94bf-c4c190c3c7f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='© 2013-2020 TOOLSQA.COM | ALL RIGHTS RESERVED.'])[1]/preceding::div[19]</value>
      <webElementGuid>9d830d8b-d805-42e3-9b2f-144c1c8f6208</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Where does it come from?']/parent::*</value>
      <webElementGuid>d984f4be-4961-437c-9f00-8fe87d6224c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div</value>
      <webElementGuid>2e9dce07-0476-47c3-b230-1b0bf7c1c065</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'section2Heading' and (text() = 'Where does it come from?' or . = 'Where does it come from?')]</value>
      <webElementGuid>7810b44f-a9a8-45f2-972d-b224ef035bdc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
