<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_RedBlueGreenYellowPurpleBlackWhiteVo_537a50</name>
   <tag></tag>
   <elementGuidId>ea34bd6f-7002-49a0-b1af-065c069bb3d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='oldSelectMenu']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#oldSelectMenu</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#oldSelectMenu</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>81fd6c45-a146-49e5-b264-c549cc9acd4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>oldSelectMenu</value>
      <webElementGuid>345f222a-eea2-4232-87e1-3a42a8e32c4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>RedBlueGreenYellowPurpleBlackWhiteVoiletIndigoMagentaAqua</value>
      <webElementGuid>2bee10f6-e78a-4d19-bd38-23e4f4911a69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;oldSelectMenu&quot;)</value>
      <webElementGuid>c66ff583-23b4-49c0-9442-ea31236910b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='oldSelectMenu']</value>
      <webElementGuid>e8f6a72d-b0f5-4e40-b20d-3c82f56e3602</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='selectMenuContainer']/div[6]/div/div/select</value>
      <webElementGuid>b448958a-727f-49cf-8d36-b55aea069a74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Old Style Select Menu'])[1]/following::select[1]</value>
      <webElementGuid>994d4870-9465-4b8a-8553-5544f5744e61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dr.'])[1]/following::select[1]</value>
      <webElementGuid>949abfe9-3351-4db3-86ea-4e68b976a32d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Multiselect drop down'])[1]/preceding::select[1]</value>
      <webElementGuid>660746d2-893d-4909-9fae-930ea5d1636f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select...'])[1]/preceding::select[1]</value>
      <webElementGuid>42cc1a3e-f52f-486c-8074-2d23d84d608e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>63297563-fce6-45d4-a539-ae2d727429ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'oldSelectMenu' and (text() = 'RedBlueGreenYellowPurpleBlackWhiteVoiletIndigoMagentaAqua' or . = 'RedBlueGreenYellowPurpleBlackWhiteVoiletIndigoMagentaAqua')]</value>
      <webElementGuid>45060732-af03-4b2e-a0bf-2694d44e50f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
